name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: |
         ping google.com -w 2
