name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: |
          echo "Variable PATH: $PATH"
          echo "Variable HOME: $HOME"
          echo "Variable GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "Variable personalizada: $HOLA"
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
