name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: |
          echo "Hello World!";
          echo hola!! >> tex.txt;
          cat tex.txt;
          ls -a
          echo $(${{ secrets.GITHUB_TOKEN }});
          echo $(${{ secrets.SSL }}) >> test.txt;
          cat test.txt;
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
