name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: Update dev branch on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          key: ${{ secrets.SSH_PASS }}
          script: |
            ls 
            cd proyect/celeste_backend_v2;
              - name: Update dev branch on EC2
      - name: TEST
        run: |
          echo ${{ $TEST.TEST }}
          echo hola!!

