name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: test
        run: |
          echo  $HOLA
          ssh -o StrictHostKeyChecking=no -i ${{secrets.SLL}} ubuntu@44.208.144.243 ls -a;

