name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: |
          echo "Variable personalizada: ${{ secrets.SLL}}";
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SLL}} ubuntu@ec2-44-208-144-243.compute-1.amazonaws.com ls -a;

