name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: |
         echo hola
      - name: scp pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          connect_timeout: 10s
          first_ssh: |
            ls -la  

