name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: |
          echo "Variable personalizada: ${{ secrets.GITHUB_TOKEN}}"
          echo ${{ secrets.SSL }} >> ssl.pem
          ssh -i ./ssl.pem ubuntu@ec2-44-208-144-243.compute-1.amazonaws.com ls -a
          echo $(ssh -v)
          echo holaa >> testt.txt
          cat testt.txt

