name: push changes to dev
on:
  push:
    branches: [dev]
jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: Update dev branch on EC2
        uses: appleboy/ssh-action@v0.1.10
        env:
          FOO: "BAR"
          BAR: "FOO"
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          key: ${{ secrets.SSH_PASS }}
          script: |
            ls
            echo $FOO 
            cd proyect/celeste_backend_v2;

