name: push changes to dev
on:
  pull_request:
    branches: [dev]

jobs:
  develop:
    permissions: write-all
    runs-on: ubuntu-20.04
    env:
      FOO: "BAR"
      GIT: "${{ github.head_ref }}"
      JSON: "${{ toJSON(github) }}"
      OTHER: "${{github.event.pull_request.head.ref}}"
    steps:
      - name: Update dev branch on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          key: ${{ secrets.SSH_PASS }} 
          envs: FOO,GIT,JSON,OTHER
          script: |
            echo "I am $FOO" 
            DEV=${GIT}
            echo "test $GIT"
            echo "test $DEV"
            echo "test $JSON"
            echo "test $OTHER"
